### ISSUE TITLE
gRPC example

### ISSUE THREAD

**Issue by Timer** [appoptics/appoptics-apm-go#93]
Could we please get a gRPC example?

**Comment by cheempz** [comment]
Hi @Timer, there's a gRPC interceptor here: https://github.com/appoptics/appoptics-apm-go/tree/master/v1/contrib/aogrpc, does it help?

**Comment by Timer** [comment]
Fantastic, thank you!

**Comment by cheempz** [comment]
Great -- closing this issue but please ping back if you have any questions, happy tracing!
